---
# tasks file for prep-portworx

- name: Check if hard disk exist
  shell: "lsblk |  grep xvdc"
  register: contentof_lsblk

- name: Only go forward is hard disk exist
  when: contentof_lsblk.stdout.find('xvdc') != -1
  debug: msg="xvdc exists"


- name: Erase disk xvdc
  shell: "dd if=/dev/zero of=/dev/xvdc bs=1M count=2"
 

    

