---
# tasks file for prep-portworx

- name: Check if hard disk exist
  shell: "lsblk |  grep {{ disk_regs_type }}"
  register: contentof_lsblk

- name: Only go forward is hard disk exist
  when: contentof_lsblk.stdout.find('{{ disk_regs_type }}') != -1
  debug: msg="{{ disk_regs_type }} exists"


- name: Erase disk {{ disk_regs_type }}
  shell: "dd if=/dev/zero of=/dev/sdb bs=1M count=2"
 

    

