- name: get the sl ssh keyid
  register: contentof_sl_sshkeys
  shell: "slcli sshkey list | grep ocp-key | awk '{print $1;}'"

- name: Fact sl ssh key 
  set_fact:
    sl_ssh_key: "{{ contentof_sl_sshkeys.stdout_lines | list }}"
 
  

  #   B1_8X16X100

################
# helper
##################
- name: create pak-helpernode vsi on sl
  expect:
    command: "slcli vs create --hostname={{ item }} --domain={{ base_domain_prefix }}.{{ base_domain }} -f B1_4X8X100 -o CENTOS_LATEST_64  --datacenter={{ sl_datacenter }} --billing=hourly  -k ocp-key  --private --vlan-private={{ sl_vlan_id }} --network 100"
    responses: 
      (?i)Continue?: "y"
  register: contentof_pak_helpernode_info
  with_items: "{{ sl_ocp_pak_helpernode }}"
  loop_control:
        pause: 15 

# A helpful reminder of what to look out for post-update.
- pause:
    minutes: "2"

