---

  - name: Check to see if pip is already installed.
    command: " pip --version"
    ignore_errors: false
    changed_when: false # read-only task
    check_mode: no
    register: pip_is_installed

  - name: Ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - gcc 
      - gcc-c++ 
      - python-devel 
      - cairo-devel 
      - gobject-introspection-devel 
      - cairo-gobject-devel 
      - ansible
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: installing all the required library
    pip:
      name: 
        - ansible>=2.7
        - pexpect
        - asn1crypto>=0.24.0
        - cryptography>=2.1.4
        - enum34>=1.1.6
        - httplib2>=0.9.2
        - idna>=2.6
        - ipaddress>=1.0.17
        - Jinja2>=2.10
        - keyring>=10.6.0
        - keyrings.alt>=3.0
        -  MarkupSafe>=1.0
        - paramiko>=2.0.0
        - pyasn1>=0.4.2
        - pycrypto>=2.6.1
        - pygobject>=3.26.1
        - pyxdg>=0.25
        - PyYAML>=3.12
        - SecretStorage>=2.3.1
        - six>=1.11.0
        - softlayer
      state: forcereinstall
        
 


  






   

