---

  - name: Check to see if pip is already installed.
    command: " pip --version"
    ignore_errors: false
    changed_when: false # read-only task
    check_mode: no
    register: pip_is_installed

  - name: Ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - gcc 
      - gcc-c++ 
      - python-devel 
      - cairo-devel 
      - gobject-introspection-devel 
      - cairo-gobject-devel 
      - ansible
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  
        
 


  






   

