
###############################################
# Get info for all the pak helper node
###############################################

 - name: Get Helpernode hostinfo
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_pak_helpernodes
   with_items: " {{ sl_ocp_pak_helpernode }}"

 - name: registering the entire list to new variable helper
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_pak_helpernodes.results }}"
   register: contentof_pak_helpernodes_stdout

 - name: Add IP information to helper hosts variable
   set_fact:
     allpakhelpernodehostsinfo: "{{ allpakhelpernodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allpakhelpernodehostids: "{{ allpakhelpernodehostids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_pak_helpernodes_stdout.results }}"




###############################################
# Get info for all the helper nodes 
###############################################

 - name: Get Helpernode hostinfo
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_helpernodes
   with_items: " {{ sl_ocp_helpernode }}"

 - name: registering the entire list to new variable helper
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_helpernodes.results }}"
   register: contentof_helpernodes_stdout

 - name: Add IP information to helper hosts variable
   set_fact:
     allhelpernodehostsinfo: "{{ allhelpernodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allhelpernodehostids: "{{ allhelpernodehostids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_helpernodes_stdout.results }}"





##############################################
# Get info for all the stroage worker nodes 
###############################################

 - name: Get Storage Workernodes hostinfo for Cloud pak for dataresult
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_storage_workernodes
   with_items: " {{ sl_ocp_portworx_storage_workers }}"




 - name: registering the entire list to new variable
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_storage_workernodes.results }}"
   register: contentof_storage_workernodes_stdout
 


 - name: Add IP information to hosts variable
   set_fact:
     allstorageworkernodehostsinfo: "{{ allstorageworkernodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allstorageworkernodehostsids: "{{ allstorageworkernodehostsids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_storage_workernodes_stdout.results }}"

##########
## Storage for OCP-registry
########

 - name: Get Storage Workernodes hostinfo for OCP-registry for dataresult
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_storage_registry_workernodes
   with_items: " {{ sl_ocp_registry_storage_worker }}"

 - name: registering the entire list to new variable
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_storage_registry_workernodes.results }}"
   register: contentof_storage_registry_workernodes_stdout


 - name: Add IP information to hosts variable
   set_fact:
     allstoragocregistryeworkernodehostsinfo: "{{ allstoragocregistryeworkernodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allstorageocregistryworkernodehostsids: "{{ allstorageocregistryworkernodehostsids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_storage_registry_workernodes_stdout.results }}"





##############################################
# Get info for all the worker nodes 
###############################################

 - name: Get Workernodes hostinfo
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_workernodes
   with_items: " {{ sl_ocp_workers }}"




 - name: registering the entire list to new variable
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_workernodes.results }}"
   register: contentof_workernodes_stdout
 


 - name: Add IP information to hosts variable
   set_fact:
     allworkernodehostsinfo: "{{ allworkernodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allworkernodehostsids: "{{ allworkernodehostsids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_workernodes_stdout.results }}"
 

# Print out all the host info

#  - name: debug
#    debug:
#      var: allworkernodehostsinfo
#  - name: debug
#    debug:
#      var: allhelpernodehostsinfo
#  - name: debug
#    debug:
#      var: allbootstrapnodehostsinfo
#  - name: debug
#    debug:
#      var: allmasternodehostsinfo



### write out the host file 
 - name: Write out host into to a file
   template:
     src: "{{ role_path }}/templates/allhostinfo.j2"
     dest: "{{ role_path }}/../../artifacts/hosts"

 - name: Remove file (delete file)
   file:
     path: "{{ role_path }}/../../artifacts/main.yml"
     state: absent
 
 - name: Write out host into to a file
   template:
     src: "{{ role_path }}/templates/allhostic4gids.j2"
     dest: "{{ role_path }}/../../artifacts/main.yml"
  

 

            