- name: Install yum podman
  yum:
    name: podman
    state: latest

- name: get route for openshift-image-registry to validate
  shell:  "podman login -u ibmicpd4pwxoem -p saiGhavai8ah docker.io"



- name: pull portworx container
  shell: "{{item}}"
  with_items:
    - podman pull gcr.io/google_containers/kube-controller-manager-amd64:v1.16.2
    - podman pull gcr.io/google_containers/kube-scheduler-amd64:v1.16.2
    - podman pull k8s.gcr.io/pause:3.1
    - podman pull quay.io/openstorage/csi-attacher:v1.2.1-1
    - podman pull quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    - podman pull quay.io/openstorage/csi-provisioner:v1.3.0-1
    - podman pull quay.io/openstorage/csi-snapshotter:v1.2.0-1
    - podman pull quay.io/openstorage/csi-resizer:v0.2.0-1
    - podman pull docker.io/openstorage/stork:2.3.3
    - podman pull docker.io/portworx/autopilot:1.0.0
    - podman pull docker.io/portworx/px-lighthouse:2.0.7
    - podman pull docker.io/portworx/lh-config-sync:2.0.7
    - podman pull docker.io/portworx/lh-stork-connector:2.0.7
    - podman pull docker.io/portworx/px-node-wiper:2.1.4
    - podman pull docker.io/portworx/oci-monitor:2.5.0.1
    - podman pull docker.io/portworx/px-enterprise-ibm-icp4d-oem:2.5.0.1
    - podman pull docker.io/portworx/px-operator:1.3.0
    - podman pull docker.io/portworx/talisman:latest

