---
# tasks file for prep-portworx

- name: Check if hard disk exist
  shell: "lsblk |  grep {{ disk1_ptx_type }}"
  register: contentof_lsblk

- name: Only go forward is hard disk exist
  when: contentof_lsblk.stdout.find('{{ disk1_ptx_type }}') != -1
  debug: msg="{{ disk1_ptx_type }} exists"

- name:  Check if hard disk exist
  shell: "lsblk |  grep {{ disk2_ptx_type }}"
  register: contentof_lsblk

- name: Only go forward is hard disk exist
  when: contentof_lsblk.stdout.find('{{ disk2_ptx_type }}') != -1
  debug: msg="{{ disk2_ptx_type }} exists"
    
- name: Erase disk {{ disk1_ptx_type }}
  shell: "dd if=/dev/zero of=/dev/{{ disk1_ptx_type }} bs=1M count=2"
 
- name: Erase disk {{ disk2_ptx_type }}
  shell: "dd if=/dev/zero of=/dev/{{ disk2_ptx_type }} bs=1M count=2"
    

