---
# handlers file for update-pakhelper-nodes


- name: restart docker
  service:
    state: restarted
    name: docker
    enabled: yes

- name: cleanup openshift login
  file: path="{{ kubeconfig | dirname }}" state=absent
